<?php
/**
 * GeneratePress child theme functions and definitions.
 *
 */

 /**
  * Load our translation files for this theme
  */
 function iwar_localization(){
     load_theme_textdomain('iwar-theme', get_stylesheet_directory() . '/languages');
 }
 add_action('after_setup_theme', 'iwar_localization');


// Load theme CSS autogenerated by sass
function iwar_files() {
    wp_enqueue_style('iwar-main', get_stylesheet_directory_uri() . '/css/main.css', array(), '1.0' );
}
add_action('wp_enqueue_scripts', 'iwar_files');

// Register additional functionality
function iwar_functionality( $features ) {
    foreach( $features as $feature ) {
      $feature_path = get_stylesheet_directory() . '/includes/' . $feature . '.php';
      if(file_exists($feature_path)) {
        require_once($feature_path);
      }
    }
}

iwar_functionality(array(
  'wordpress-tweaks',
  'bbpress-tweaks',
));