<?php
function iwar_files() {
    // Autogenerated Bootstrap CSS
    wp_enqueue_style('bootstrap-main', get_stylesheet_directory_uri() . '/css/main.css', array(), '1.0' );
    // Bootstrap JS Bundle
    wp_enqueue_script('bootstrap', get_stylesheet_directory_uri() . '/node_modules/bootstrap/dist/js/bootstrap.bundle.min.js', array( 'jquery' ), '5.2.3', true );
    // Theme CSS
    wp_enqueue_style('iwar-main', get_stylesheet_uri(), array('bootstrap-main'), '1.0.0');
}
add_action('wp_enqueue_scripts', 'iwar_files');

function iwar_features() {
  add_theme_support('title-tag');
  add_theme_support('post-thumbnails');
  add_theme_support( 'align-wide' );
  add_image_size('iwar_thumb', 800, 800, true);
  add_image_size('iwar_thumb_wide', 800, 450, true);
  add_image_size('iwar_slide', 1920, 1080, true);
  $logo_defaults = array(
      'height'               => 100,
      'width'                => 400,
      'flex-height'          => true,
      'flex-width'           => true,
      'header-text'          => array( 'site-title', 'site-description' ) 
    );
  add_theme_support( 'custom-logo', $logo_defaults );
}
add_action('after_setup_theme', 'iwar_features');

function register_iwar_menus() {
  register_nav_menus(
    array(
      'main-menu'     => __( 'Main Menu' ),
      'footer-left' => __( 'Footer (left)' ),
      'footer-center'    => __( 'Footer (center)' ),
      'footer-right'    => __( 'Footer (right)' ),
      'footer-bottom' => __( 'Footer (bottom)' ),
    )
  );
}
add_action( 'init', 'register_iwar_menus' );

function register_functionality( $features ) {
    foreach( $features as $feature ) {
      $feature_path = get_stylesheet_directory() . '/includes/' . $feature . '.php';
      if(file_exists($feature_path)) {
        require_once($feature_path);
      }
    }
}

register_functionality(array(
    'wordpress-tweaks'
));