<?php

/**
 * Registers support for Gutenberg features.
 * Only features that are not manageable via theme.json
 * are configured here.
 * 
 */
function iwar_gutenberg_css() {
	// Enable theme support for custom backend styles
	add_theme_support( 'editor-styles' );

    // Include our autogenerated main.css in the backend editor view
    add_editor_style( [
        'css/main.css',
    ] );
}
add_action( 'after_setup_theme', 'iwar_gutenberg_css' );

// Disable external blocks from block directory
remove_action( 'enqueue_block_editor_assets', 'wp_enqueue_editor_block_directory_assets' );

/* Gutenberg overrides / settings (backend) */
function iwar_editor_assets() {
	// Editor overrides
	wp_register_script(
        'theme-editor',
        get_stylesheet_directory_uri() . '/assets/js/theme-editor.js',
        [ 'wp-blocks', 'wp-dom', 'wp-dom-ready', 'wp-edit-post' ],
        filemtime( get_stylesheet_directory() . '/assets/js/theme-editor.js' )
    );
    wp_enqueue_script( 'theme-editor' );
}
add_action( 'enqueue_block_editor_assets', 'gpm_editor_assets' );