<?php
/**
 * Gutenberg core behaviour overrides.
 *
 * @package iwar-theme
 * @author Danny Schmarsel <ds@lichtmetzger.de>
 */

namespace IwarTheme;

if ( ! defined( 'ABSPATH' ) ) {
	die( '' );
}

/**
 * Registers Gutenberg tweaks.
 */
class Gutenberg {
	/**
	 * Initialization function.
	 *
	 * @return void
	 */
	public function initialize() {
		add_action( 'after_setup_theme', array( $this, 'register_features' ) );

		// Disable external blocks from the block directory.
		remove_action( 'enqueue_block_editor_assets', 'wp_enqueue_editor_block_directory_assets' );

		add_action( 'enqueue_block_editor_assets', array( $this, 'manage_assets' ) );
	}

	/**
	 * Registers support for Gutenberg features.
	 * Only features that are not manageable via theme.json
	 * are configured here.
	 *
	 * @return void
	 */
	public function register_features() {
		// Enable theme support for custom backend styles.
		add_theme_support( 'editor-styles' );

		// Include our autogenerated main.css in the backend editor view.
		add_editor_style(
			array(
				'css/main.css',
			)
		);
	}

	/**
	 * Loads additional assets for the Gutenberg editor.
	 *
	 * @return void
	 */
	public function manage_assets() {
		wp_register_script(
			'theme-editor',
			get_stylesheet_directory_uri() . '/assets/js/theme-editor.js',
			array( 'wp-blocks', 'wp-dom', 'wp-dom-ready', 'wp-edit-post' ),
			filemtime(
				get_stylesheet_directory() . '/assets/js/theme-editor.js'
			),
			true
		);
		wp_enqueue_script( 'theme-editor' );

	}
}
